baseURL: "https://yahya-derbeli.netlify.app"
languageCode: "en-us"
title: "Yahya Derbeli"
theme: "./.."
relativeURLs: true

googleanalytics: UA-xxxxxx-x
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3
  customCSS: false

  favicon: "/images/fav.png"
  description: "My personal portfolio website"


  # home
  disable_home: false
  profile_image: "/images/portrait photo.png"
  name: "Yahya Derbeli"
  namecolor: ffc107
  profession: "A software consultant at Talan Tunisie"
  github: "https://github.com/yahya971"
  linkedin: "https://www.linkedin.com/in/yahya-derbeli"

  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Yahya Derbeli, your go-to software engineer!"
  descripe_l2_person: "Have a taste of some of my finest projects [here](#projects)"
  skills:
    - name: Business Intelligence
      percentage: 90
    - name: Machine Learning
      percentage: 85
    - name: Angular
      percentage: 80
    - name: Nest.js
      percentage: 70

  # Experience
  disable_experience: false
  experience:
    - company: "Talan Tunisie"
      id: "TALAN"
      role: "Software Consultant"
      startdate: Feb 2021
      enddate: present
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "BIAT"
      id: "BIAT" 
      role: "Business Intelligence Intern"
      startdate: Jul 2020
      enddate: Sep 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Smart Solutions Consulting"
      id: "SSC"
      role: "Fullstack Developer Intern"
      startdate: Jul 2019
      enddate: Sep 2029
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Spectrum Consulting"
      id: "Spectrum" 
      role: "ERP/Intranet Intern"
      startdate: Jul 2018
      enddate: Aug 2018
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.

  # Education
  disable_education: false
  education:
    - degree: "Software Engineer"
      branch: "Data Science"
      university: "INSAT"
      startedyear: "2016"
      graduation: "2021"
    - degree: "Baccalaureat"
      branch: "Mathematics"
      university: "Boukornine High School"
      startedyear: "2012"
      graduation: "2016"


  # Projects
  disable_projects: false
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: false
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      # url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "example@mail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
